-- SELECT > FROM > WHERE > GROUP BY > HAVING > ORDER BY > LIMIT

-- SELECT
SELECT 'Hola, Praveen!';

-- FROM
SELECT * FROM TABLE_NAME;

SELECT * FROM TABLE_NAME1 T1 INNER JOIN TABLE_NAME2 T2 ON T1.T_ID = T2.T_ID; -- INNER JOIN

SELECT * FROM TABLE_NAME1 T1 RIGHT JOIN TABLE_NAME2 T2 ON T1.T_ID = T2.T_ID; -- RIGHT JOIN

SELECT * FROM TABLE_NAME1 T1 LEFT JOIN TABLE_NAME2 T2 ON T1.T_ID = T2.T_ID; -- LEFT JOIN

SELECT * FROM TABLE_NAME1 T1 RIGHT JOIN TABLE_NAME2 T2 ON T1.T_ID = T2.T_ID
UNION
SELECT * FROM TABLE_NAME1 T1 LEFT JOIN TABLE_NAME2 T2 ON T1.T_ID = T2.T_ID; -- FULL JOIN

-- WHERE
SELECT * FROM TABLE_NAME WHERE T_ID IS NOT NULL;

-- GROUP BY
SELECT 
    AVG(T_SALARY) AVERAGE_SALARY, 
    T_ID, 
    T_DEPT 
FROM TABLE_NAME 
WHERE T_ID IS NOT NULL
GROUP BY T_ID, T_DEPT;

-- HAVING
SELECT 
    AVG(T_SALARY) AVERAGE_SALARY, 
    T_ID, 
    T_DEPT 
FROM TABLE_NAME 
WHERE T_ID IS NOT NULL
GROUP BY T_ID, T_DEPT
HAVING AVG(T_SALARY) > 35000;

-- ORDER BY
SELECT 
    AVG(T_SALARY) AS AVERAGE_SALARY, 
    T_ID, 
    T_DEPT,
    MAX(T_CREATED_ON) AS LAST_CREATED
FROM TABLE_NAME
WHERE T_ID IS NOT NULL
GROUP BY T_ID, T_DEPT
HAVING AVG(T_SALARY) > 35000
ORDER BY LAST_CREATED DESC;

-- LIMIT
SELECT 
    AVG(T_SALARY) AS AVERAGE_SALARY, 
    T_ID, 
    T_DEPT,
    MAX(T_CREATED_ON) AS LAST_CREATED
FROM TABLE_NAME
WHERE T_ID IS NOT NULL
GROUP BY T_ID, T_DEPT
HAVING AVG(T_SALARY) > 35000
ORDER BY LAST_CREATED DESC
LIMIT 100;